<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TipoMonitorias extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('tipo_monitorias')->insert([
            ['nombre' => 'Administrativa'],
            ['nombre' => 'Académica'],
            ['nombre' => 'Investigación'],
            ['nombre' => 'Técnica'],
            ['nombre' => 'Deportiva'],
            ['nombre' => 'Cultural'],
            ['nombre' => 'Social'],
            ['nombre' => 'Ambiental'],
            ['nombre' => 'Empresarial'],
            ['nombre' => 'Tecnológica'],
            ['nombre' => 'Artística'],
            ['nombre' => 'Psicológica'],
            ['nombre' => 'Lingüística'],
            ['nombre' => 'Histórica'],
            ['nombre' => 'Geográfica'],
            ['nombre' => 'Matemática'],
            ['nombre' => 'Física'],
            ['nombre' => 'Química'],
            ['nombre' => 'Biológica'],
            ['nombre' => 'Informática'],
            ['nombre' => 'Educativa'],
            ['nombre' => 'Literaria'],
            ['nombre' => 'Musical'],
            ['nombre' => 'Teatral'],
            ['nombre' => 'Cinematográfica'],
            ['nombre' => 'Fotográfica'],
            ['nombre' => 'Arquitectónica'],
            ['nombre' => 'Diseño'],
            ['nombre' => 'Gastronómica'],
            ['nombre' => 'Deportivo'],
            ['nombre' => 'Turística'],
            ['nombre' => 'Voluntariado'],
            ['nombre' => 'Emprendimiento'],
            ['nombre' => 'Innovación'],
            ['nombre' => 'Sostenibilidad'],
            ['nombre' => 'Salud'],
            ['nombre' => 'Bienestar'],
            ['nombre' => 'Seguridad'],
            ['nombre' => 'Transporte'],
            ['nombre' => 'Logística'],
            ['nombre' => 'Financiera'],
            ['nombre' => 'Comunicacional'],
            ['nombre' => 'Administración Pública'],
            ['nombre' => 'Derecho'],
            ['nombre' => 'Ingeniería'],
            ['nombre' => 'Arquitectura'],
            ['nombre' => 'Ciencias Sociales'],
            ['nombre' => 'Ciencias Naturales'],
            ['nombre' => 'Ciencias Exactas'],
            ['nombre' => 'Ciencias de la Salud'],
            ['nombre' => 'Ciencias de la Educación'],
            ['nombre' => 'Ciencias Económicas'],
            ['nombre' => 'Ciencias Políticas'],
            ['nombre' => 'Ciencias Ambientales'],
            ['nombre' => 'Ciencias de la Comunicación'],
            ['nombre' => 'Ciencias de la Información'],
            ['nombre' => 'Ciencias de la Computación'],
            ['nombre' => 'Ciencias de la Ingeniería'],
            ['nombre' => 'Ciencias de la Administración'],
            ['nombre' => 'Ciencias de la Contaduría'],
            ['nombre' => 'Ciencias de la Psicología'],
            ['nombre' => 'Ciencias de la Sociología'],
            ['nombre' => 'Ciencias de la Antropología'],
            ['nombre' => 'Jurídica'],
            ['nombre' => 'Política'],
            ['nombre' => 'Económica'],
            ['nombre' => 'Social'],
            ['nombre' => 'Científica'],
            ['nombre' => 'Tecnológica'],
            ['nombre' => 'Investigativa'],
            ['nombre' => 'Desarrollo Comunitario'],                                 
            ['nombre' => 'Educación Continua'],
            ['nombre' => 'Capacitación Profesional'],
            ['nombre' => 'Formación Integral'],
            ['nombre' => 'Orientación Vocacional'],
            ['nombre' => 'Asesoría Psicológica'],
            ['nombre' => 'Apoyo Académico'],
            ['nombre' => 'Mentoría Estudiantil'],
            ['nombre' => 'Acompañamiento Pedagógico'],
            ['nombre' => 'Desarrollo Personal'],
            ['nombre' => 'Crecimiento Profesional'],
        ]);
    }
}
